name: Flutter Firebase Deployment
on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0' # Replace with the desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Authenticate with Firebase
        run: |
          echo $FIREBASE_TOKEN | firebase login --no-localhost

      - name: Deploy to Firebase Hosting
        run: |
          firebase use --token $FIREBASE_TOKEN # Replace with your Firebase project alias
          firebase deploy --only hosting --token $FIREBASE_TOKEN
