name: Flutter Firebase Deployment
on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the version of Node.js that is compatible with Firebase CLI.

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6' # Replace with the desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Authenticate with Firebase
        run: |
          echo $FIREBASE_TOKEN | firebase login --no-localhost

      - name: Deploy to Firebase Hosting
        run: |
          firebase use --token $FIREBASE_TOKEN # Replace with your Firebase project alias
          firebase deploy --only hosting --token $FIREBASE_TOKEN
